# Sử dụng image Node.js phiên bản 18 làm base image
FROM node:18

# Đặt thư mục làm việc trong container
WORKDIR /app

ENV NODE_ENV=production

# Copy package.json và package-lock.json để cài đặt dependencies
COPY package*.json ./

# Cài đặt dependencies
RUN npm install

# Copy toàn bộ mã nguồn vào container
COPY . .

EXPOSE 5000

# Lệnh để chạy ứng dụng
CMD ["node", "src/index.js"]