# Sử dụng image Node.js phiên bản 18 làm base image
FROM node:18

# Đặt thư mục làm việc trong container
WORKDIR /app

# Copy package.json và package-lock.json để cài đặt dependencies
COPY package*.json ./

# Cài đặt dependencies
RUN npm install

# Copy toàn bộ mã nguồn vào container
COPY . .

# Mở cổng mà ứng dụng sẽ chạy (cổng 3000, theo ServerConfig.PORT)
EXPOSE 5000

# Lệnh để chạy ứng dụng
CMD ["node", "src/index.js"]