-- Tạo database nếu chưa có (MySQL không cần schema "public", vì schema trong MySQL chính là database)
CREATE DATABASE IF NOT EXISTS flightbooking;
USE flightbooking;

-- Tạo bảng Users
CREATE TABLE IF NOT EXISTS Users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Tạo bảng Roles
CREATE TABLE IF NOT EXISTS Roles (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Tạo bảng User_Roles
CREATE TABLE IF NOT EXISTS User_Roles (
  UserId INT NOT NULL,
  RoleId INT NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (UserId, RoleId),
  FOREIGN KEY (UserId) REFERENCES Users(id),
  FOREIGN KEY (RoleId) REFERENCES Roles(id)
);

-- Tạo bảng SequelizeMeta (cho Sequelize migrations)
CREATE TABLE IF NOT EXISTS SequelizeMeta (
  name VARCHAR(255) NOT NULL PRIMARY KEY
);

-- Tạo bảng Airplanes
CREATE TABLE IF NOT EXISTS Airplanes (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  modelNumber VARCHAR(50) NOT NULL,
  capacity INT NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Tạo bảng Cities
CREATE TABLE IF NOT EXISTS Cities (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Tạo bảng Airports
CREATE TABLE IF NOT EXISTS Airports (
  id VARCHAR(10) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  code VARCHAR(10) NOT NULL UNIQUE,
  address VARCHAR(255),
  cityId INT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (cityId) REFERENCES Cities(id)
);

-- Tạo bảng Flights
CREATE TABLE IF NOT EXISTS Flights (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  flightNumber VARCHAR(20) NOT NULL UNIQUE,
  airplaneId INT,
  departureAirportId VARCHAR(10),
  arrivalAirportId VARCHAR(10),
  arrivalTime TIMESTAMP NOT NULL,
  departureTime TIMESTAMP NOT NULL,
  price INT NOT NULL,
  boardingGate VARCHAR(10),
  totalSeats INT NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (airplaneId) REFERENCES Airplanes(id),
  FOREIGN KEY (departureAirportId) REFERENCES Airports(id),
  FOREIGN KEY (arrivalAirportId) REFERENCES Airports(id)
);

-- Tạo bảng Seats
CREATE TABLE IF NOT EXISTS Seats (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  airplaneId INT,
  seatRow INT NOT NULL,
  col VARCHAR(5) NOT NULL,
  seatType VARCHAR(50) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (airplaneId) REFERENCES Airplanes(id)
);

-- Tạo bảng Bookings
CREATE TABLE IF NOT EXISTS Bookings (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  flightId INT,
  userId INT,
  status VARCHAR(20) NOT NULL,
  noOfSeats INT NOT NULL,
  totalCost INT NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (flightId) REFERENCES Flights(id),
  FOREIGN KEY (userId) REFERENCES Users(id)
);

-- Tạo bảng Tickets (dành cho Notification-Service)
CREATE TABLE IF NOT EXISTS Tickets (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  bookingId INT,
  recipientEmail VARCHAR(255) NOT NULL,
  departureTime TIMESTAMP NOT NULL,
  arrivalTime TIMESTAMP NOT NULL,
  noOfSeats INT NOT NULL,
  status VARCHAR(50) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (bookingId) REFERENCES Bookings(id)
);






-- Chèn dữ liệu vào bảng Flights

-- Chèn dữ liệu vào bảng Bookings

